// app/jobs/dummyJobs.ts
export const jobs = [
  {
    id: 1,
    slug: "senior-graphic-designer",
    title: "Senior Graphic Designer",
    company: "Creative Labs",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://creativelabs.com",
    industry: "Design & Marketing",
    size: "200-500 employees",
    location: "New York City, NY",
    time: "2h",
    type: "Full-time",
    mode: "Onsite",
    deadline: "Oct 15, 2025",
    salary: "$120k - $150k",
    skills: ["Photoshop", "Illustrator", "Branding", "Leadership"],
    description:
      "Lead creative direction for campaigns, oversee design assets, and mentor junior designers. Work closely with marketing and content teams to ensure all designs align with brand guidelines.",
    requirements: [
      "5+ years of experience in graphic design",
      "Proficiency in Adobe Creative Suite",
      "Strong typography and layout skills",
      "Experience leading design projects and mentoring juniors",
    ],
    responsibilities: [
      "Collaborate with creative directors and marketing teams",
      "Oversee design projects from concept to delivery",
      "Develop design systems and brand guidelines",
      "Stay up-to-date with industry trends and tools",
    ],
  },
  {
    id: 2,
    slug: "frontend-engineer",
    title: "Frontend Engineer",
    company: "CodeWorks",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://codeworks.com",
    industry: "Software Development",
    size: "100-200 employees",
    location: "Berlin, Germany",
    time: "1d",
    type: "Full-time",
    mode: "Hybrid",
    deadline: "Oct 20, 2025",
    salary: "$100k - $130k",
    skills: ["React", "TypeScript", "Next.js", "CSS"],
    description:
      "Build responsive user interfaces with React, optimize performance, and ensure accessibility. Collaborate with backend engineers and designers to deliver scalable web applications.",
    requirements: [
      "3+ years of experience with React and TypeScript",
      "Strong knowledge of HTML, CSS, and JavaScript",
      "Experience with Next.js",
      "Understanding of accessibility and performance optimization",
    ],
    responsibilities: [
      "Develop and maintain frontend features",
      "Work closely with UI/UX designers",
      "Optimize web applications for speed and scalability",
      "Participate in code reviews and mentoring",
    ],
  },
  {
    id: 3,
    slug: "ux-ui-designer",
    title: "UX/UI Designer",
    company: "Tech Genius",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://techgenius.com",
    industry: "Technology",
    size: "500-1000 employees",
    location: "San Francisco, CA",
    time: "4h",
    type: "Full-time",
    mode: "Remote",
    deadline: "Oct 10, 2025",
    salary: "$130k - $160k",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping"],
    description:
      "Design user-friendly interfaces and collaborate with developers to improve product usability. Lead usability testing and analyze results to drive design decisions.",
    requirements: [
      "4+ years of experience in UX/UI design",
      "Proficiency in Figma, Sketch, or Adobe XD",
      "Experience in user research and testing",
      "Strong visual design and interaction skills",
    ],
    responsibilities: [
      "Create wireframes, prototypes, and visual designs",
      "Collaborate with product managers and developers",
      "Conduct usability testing and iterate on designs",
      "Ensure consistency in design systems across products",
    ],
  },
];
