import { ApplyType, Job } from "@/features/jobs/types/jobSlug";

export const jobs: Job[] = [
  {
    id: 1,
    slug: "privacy-consultant",
    title: "Senior Graphic Designer",
    role: "Design Lead",
    company: "Creative Labs",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://creativelabs.com",
    industry: "Design & Marketing",
    size: "200-500 employees",
    location: "New York City, NY",
    time: "2h",
    type: "Full-time",
    mode: "ONSITE",
    deadline: "Oct 15, 2025",
    salary: "$120k - $150k",
    skills: ["Photoshop", "Illustrator", "Branding", "Leadership"],
    certifications: ["Adobe Certified Expert (ACE)"],
    description:
      "Lead creative direction for campaigns, oversee design assets, and mentor junior designers. Work closely with marketing and content teams to ensure all designs align with brand guidelines.",
    applyType: ApplyType.DIRECT, // ✅ no applyUrl, no questions
    experienceLevel: "SENIOR",
    postedAt: "2025-09-20",
  },
  {
    id: 2,
    slug: "frontend-engineer",
    title: "Frontend Engineer",
    role: "Software Engineer",
    company: "CodeWorks",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://codeworks.com",
    industry: "Software Development",
    size: "100-200 employees",
    location: "Berlin, Germany",
    time: "1d",
    type: "Full-time",
    mode: "HYBRID",
    deadline: "Oct 20, 2025",
    salary: "$100k - $130k",
    skills: ["React", "TypeScript", "Next.js", "CSS"],
    certifications: ["Certified React Developer", "TypeScript Advanced Certification"],
    description:
      "Build responsive user interfaces with React, optimize performance, and ensure accessibility. Collaborate with backend engineers and designers to deliver scalable web applications.",
    applyType: ApplyType.DIRECT, // ✅ no applyUrl, no questions
    experienceLevel: "MID",
    postedAt: "2025-09-18",
  },
  {
    id: 3,
    slug: "ux-ui-designer",
    title: "UX/UI Designer",
    role: "UX/UI Specialist",
    company: "Tech Genius",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://techgenius.com",
    industry: "Technology",
    size: "500-1000 employees",
    location: "San Francisco, CA",
    time: "4h",
    type: "Full-time",
    mode: "REMOTE",
    deadline: "Oct 10, 2025",
    salary: "$130k - $160k",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping"],
    certifications: ["Certified UX Designer (CXD)"],
    description:
      "Design user-friendly interfaces and collaborate with developers to improve product usability. Lead usability testing and analyze results to drive design decisions.",
    applyType: ApplyType.PRE_SCREENING,
    questions: [ // ✅ questions array required
      "Why do you want to work at Tech Genius?",
      "Share a portfolio link with your best UX/UI work.",
      "How do you handle usability testing feedback?"
    ],
    experienceLevel: "SENIOR",
    postedAt: "2025-09-15",
  },
  {
    id: 4,
    slug: "data-scientist",
    title: "Data Scientist",
    role: "Data Analyst/Scientist",
    company: "DataHive",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://datahive.com",
    industry: "Analytics & AI",
    size: "50-100 employees",
    location: "Austin, TX",
    time: "3h",
    type: "Full-time",
    mode: "REMOTE",
    deadline: "Oct 25, 2025",
    salary: "$110k - $140k",
    skills: ["Python", "Machine Learning", "SQL", "Data Visualization"],
    certifications: ["AWS Certified Machine Learning", "Certified Data Scientist (CDS)"],
    description:
      "Analyze complex datasets to derive insights, build predictive models, and create visual dashboards. Work closely with product and engineering teams to support data-driven decisions.",
    applyType: ApplyType.EXTERNAL,
    applyUrl: "https://datahive.com/careers/data-scientist", // ✅ required for external
    experienceLevel: "MID",
    postedAt: "2025-09-17",
  },
  {
    id: 5,
    slug: "backend-developer",
    title: "Backend Developer",
    role: "Backend Engineer",
    company: "DevCore",
    companyLogo: "https://via.placeholder.com/100",
    website: "https://devcore.com",
    industry: "Software Development",
    size: "200-500 employees",
    location: "Toronto, Canada",
    time: "5h",
    type: "Full-time",
    mode: "HYBRID",
    deadline: "Oct 30, 2025",
    salary: "$105k - $135k",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
    certifications: ["Node.js Certified Developer", "MongoDB Certified Developer"],
    description:
      "Design, develop, and maintain server-side logic and APIs. Ensure high performance and responsiveness of applications. Collaborate with frontend developers for seamless integration.",
    applyType: ApplyType.DIRECT, // ✅ no applyUrl, no questions
    experienceLevel: "MID",
    postedAt: "2025-09-19",
  },
];
