import { Job } from "@/features/jobs/types/jobs";

export const jobs: Job[] = [
  {
    id: 1,
    title: "Senior Graphic Designer",
    slug: "senior-graphic-designer",
    company: "Creative Labs",
    location: "New York",
    mode: "Onsite",
    type: "Full-time",
    experienceLevel: "Senior Level",
    postedAt: "2025-09-20",
    description:
      "Lead creative direction for campaigns, oversee design assets, and mentor junior designers.",
  },
  {
    id: 2,
    title: "UX/UI Designer",
    slug: "ux-ui-designer",
    company: "Tech Genius",
    location: "San Francisco",
    mode: "Remote",
    type: "Full-time",
    experienceLevel: "Mid Level",
    postedAt: "2025-09-18",
    description:
      "Design user-friendly interfaces and collaborate with developers to improve product usability.",
  },
  {
    id: 3,
    title: "Magazine Art Director",
    slug: "magazine-art-director",
    company: "TrendSetters",
    location: "London",
    mode: "Hybrid",
    type: "Full-time",
    experienceLevel: "Senior Level",
    postedAt: "2025-09-15",
    description:
      "Oversee magazine layout, manage photography sessions, and ensure brand consistency.",
  },
  {
    id: 4,
    title: "Motion Graphics Designer",
    slug: "motion-graphics-designer",
    company: "DigitalDreams",
    location: "Los Angeles",
    mode: "Remote",
    type: "Full-time",
    experienceLevel: "Mid Level",
    postedAt: "2025-09-12",
    description:
      "Create engaging motion graphics for ads, video content, and brand campaigns.",
  },
  {
    id: 5,
    title: "Frontend Engineer",
    slug: "frontend-engineer",
    company: "CodeWorks",
    location: "Berlin",
    mode: "Hybrid",
    type: "Full-time",
    experienceLevel: "Mid Level",
    postedAt: "2025-09-10",
    description:
      "Build responsive user interfaces with React, optimize performance, and ensure accessibility.",
  },
  {
    id: 6,
    title: "Backend Developer",
    slug: "backend-developer",
    company: "DataForge",
    location: "Toronto",
    mode: "Remote",
    type: "Contract",
    experienceLevel: "Mid Level",
    postedAt: "2025-09-08",
    description:
      "Develop scalable APIs, integrate databases, and work with cloud infrastructure.",
  },
  {
    id: 7,
    title: "Cybersecurity Analyst",
    slug: "cybersecurity-analyst",
    company: "SecureNet",
    location: "Austin",
    mode: "Onsite",
    type: "Full-time",
    experienceLevel: "Entry Level",
    postedAt: "2025-09-05",
    description:
      "Monitor security systems, respond to threats, and implement data protection measures.",
  },
  {
    id: 8,
    title: "Cloud Solutions Architect",
    slug: "cloud-solutions-architect",
    company: "SkyHigh Tech",
    location: "Sydney",
    mode: "Remote",
    type: "Full-time",
    experienceLevel: "Senior Level",
    postedAt: "2025-09-02",
    description:
      "Design and implement scalable cloud solutions using AWS, Azure, or GCP.",
  },
  {
    id: 9,
    title: "AI Research Scientist",
    slug: "ai-research-scientist",
    company: "NeuroTech Labs",
    location: "Boston",
    mode: "Hybrid",
    type: "Full-time",
    experienceLevel: "Senior Level",
    postedAt: "2025-08-30",
    description:
      "Conduct AI research, publish findings, and develop machine learning algorithms.",
  },
  {
    id: 10,
    title: "Digital Marketing Specialist",
    slug: "digital-marketing-specialist",
    company: "BrandBoost",
    location: "Dubai",
    mode: "Onsite",
    type: "Full-time",
    experienceLevel: "Mid Level",
    postedAt: "2025-08-28",
    description:
      "Manage online campaigns, optimize SEO strategies, and track marketing performance.",
  },
];
